#
# Copyright (C) 2023-2026 The LineageOS / OrangeFox Recovery Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/oneplus/udon

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a76

TARGET_USES_64_BIT_BINDER := true

# Platform
TARGET_BOARD_PLATFORM := waipio
TARGET_BOOTLOADER_BOARD_NAME := udon
TARGET_NO_BOOTLOADER := true

# A/B & Virtual A/B
ENABLE_VIRTUAL_AB := true
BOARD_USES_VIRTUAL_AB_RECOVERY := true
BOARD_USES_DYNAMIC_PARTITIONS := true

# Kernel & Boot Image Header
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)

# Partitions Sizes & Layout
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_USES_METADATA_PARTITION := true
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 104857600
BOARD_BOOTIMAGE_PARTITION_SIZE := 201326592
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 104857600
BOARD_DTBOIMG_PARTITION_SIZE := 25165824
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := oplus_dynamic_partitions
BOARD_OPLUS_DYNAMIC_PARTITIONS_SIZE := 9122611200
BOARD_OPLUS_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system \
    system_ext \
    product \
    vendor \
    vendor_dlkm \
    odm \
    odm_dlkm \
    my_product \
    my_engineering \
    my_stock \
    my_carrier \
    my_region \
    my_bigball \
    my_heytap \
    my_manifest

# Recovery Fstab
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

# TWRP & Display Configuration
TW_THEME := portrait_hdpi
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_SCREEN_BLANK_ON_BOOT := true
TW_MAX_BRIGHTNESS := 4095
TW_DEFAULT_BRIGHTNESS := 1024
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
TW_EXTRA_LANGUAGES := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_HAS_MTP := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LIBRESETPROP := true
RECOVERY_SDCARD_ON_DATA := true

# Crypto & Decryption (FBE v2 & WrappedKey)
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
BOARD_USES_QCOM_DECRYPT := true

# OrangeFox Flags
FOX_VIRTUAL_AB_DEVICE := 1
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
FOX_REPLACE_BUSYBOX_SHELL := 1
FOX_USE_BASH_SHELL := 1
FOX_USE_NANO_EDITOR := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_SED_BINARY := 1
FOX_USE_XZ_UTILS := 1
OF_ENABLE_LPTOOLS := 1
OF_KEEP_FORCED_ENCRYPTION := 1
OF_PATCH_AVB20 := 1
OF_SCREEN_H := 2772
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 1
OF_HIDE_NOTCH := 1
OF_USE_GREEN_LED := 0
OF_FLASHLIGHT_ENABLE := 1
OF_FL_PATH1 := "/sys/class/leds/led:torch_0"
OF_FL_PATH2 := "/sys/class/leds/led:torch_1"
OF_QUICK_BACKUP_LIST := "/boot;/data;/super;"
FOX_TARGET_DEVICES := "udon,aston,CPH2487,OP5961L1"
OF_ALLOW_DISABLE_NAVBAR := 0
OF_MAINTAINER := "The LineageOS Project"

# Lenient flags for minimal build system
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_BUILD_DIRS := true
ALLOW_MISSING_DEPENDENCIES := true
